### ISSUE TITLE
Network issue: java.lang.RuntimeException: Field serialization error in class aurocosh.divinefavor.common.network.message.sever.MessageRequestTemplate

### ISSUE THREAD

**Issue by noobanidus** [Aurocosh/divine-favor#17]
Someone sent me their client log and it almost entirely consists of the following:

```
[01:38:41] [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception

io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Field serialization error in class aurocosh.divinefavor.common.network.message.sever.MessageRequestTemplate
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:321) [SimpleNetworkWrapper.class:?]
	at aurocosh.autonetworklib.network.wrapped.WrappedServerMessage.send(WrappedServerMessage.java:8) [WrappedServerMessage.class:?]
	at aurocosh.divinefavor.client.core.handler.EventClientTickHandler.onClientTick(EventClientTickHandler.kt:45) [EventClientTickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1939_EventClientTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1708) [bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Field serialization error in class aurocosh.divinefavor.common.network.message.sever.MessageRequestTemplate
	at aurocosh.autonetworklib.network.serialization.class_serializers.ClassBufSerializer.toBytes(ClassBufSerializer.java:82) ~[ClassBufSerializer.class:?]
	at aurocosh.autonetworklib.network.message.NetworkAutoMessage.toBytes(NetworkAutoMessage.java:25) ~[NetworkAutoMessage.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	... 25 more
Caused by: java.lang.NullPointerException
	at aurocosh.autonetworklib.network.serialization.buf_serializers.generic.array_list.CollectionListWriter.write(CollectionListWriter.java:20) ~[CollectionListWriter.class:?]
	at aurocosh.autonetworklib.network.serialization.buf_serializers.generic.array_list.CollectionListWriter.write(CollectionListWriter.java:8) ~[CollectionListWriter.class:?]
	at aurocosh.autonetworklib.network.serialization.class_serializers.FieldBufSerializer.serialize(FieldBufSerializer.java:37) ~[FieldBufSerializer.class:?]
	at aurocosh.autonetworklib.network.serialization.class_serializers.ClassBufSerializer.toBytes(ClassBufSerializer.java:79) ~[ClassBufSerializer.class:?]
	at aurocosh.autonetworklib.network.message.NetworkAutoMessage.toBytes(NetworkAutoMessage.java:25) ~[NetworkAutoMessage.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	... 25 more
```

**Comment by Aurocosh** [comment]
Thanks for report. Fixed in 1.0.684.

**Comment by Aurocosh** [comment]
Also update Auto Network Lib before testing. Starting from version 1.0.685 version 1.0.36 of auto lib will be required.

**Comment by noobanidus** [comment]
Thanks! I generally update everything that's available, but from our own release of Roots 3 I've noticed people having issues because Twitch assumes the previous version of Mystical Lib is sufficient... Sigh.
