### ISSUE TITLE
Hard Lock and Crash when placing Bath Heater

### ISSUE THREAD

**Issue by Yoshi325** [Aurocosh/divine-favor#2]
I created a new world with creative mode on and gave myself a Bath Heater. As soon as I attempt to place it, the java instance hard locks. Inspecting the logs show:

```
22:27:58
net.minecraft.server.MinecraftServer
Server thread
error
Encountered an unexpected exception net.minecraft.util.ReportedException: Ticking block entity at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.AbstractMethodError: aurocosh.divinefavor.common.block.bath_heater.TileBathHeater.getWorld()Lnet/minecraft/world/World; at aurocosh.divinefavor.common.area.WorldAreaWatcher.registerWatcher(WorldAreaWatcher.kt:17) at aurocosh.divinefavor.common.block.bath_heater.TileBathHeater.initialize(TileBathHeater.kt:118) at aurocosh.divinefavor.common.block.bath_heater.TileBathHeater.func_73660_a(TileBathHeater.kt:212) at net.minecraft.world.World.func_72939_s(World.java:1835) at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ... 4 more
22:27:59
net.minecraft.server.MinecraftServer
Server thread
error
This crash report has been saved to: /Users/charles/Minecraft(Custom)/DivineFavor-1.0.469_Minecraft-1.12.2/crash-reports/crash-2019-05-26_22.27.59-server.txt
```

### Mods:
Forgelin-1.8.2.jar
Patchouli-1.0-19.jar
divinefavor-1.0.469.jar
jei_1.12.2-4.15.0.268.jar

**Minecraft Version:** 1.12.2

**Forge Version:** 14.23.5.2768

Crash Report is Attached. [crash-2019-05-26_22.27.59-server.txt](https://github.com/Aurocosh/divine-favor/files/3221600/crash-2019-05-26_22.27.59-server.txt)

**Comment by Aurocosh** [comment]
Try latest version and check if it fixes your problem

**Comment by Aurocosh** [comment]
Try version 1.0.476

**Comment by Xechon** [comment]
I can confirm having this problem with an earlier build, and it was resolved upon updating.

**Comment by Aurocosh** [comment]
Thanks for report @Xechon, then i will mark issue as closed.

**Comment by Yoshi325** [comment]
For what it's worth, I tried v1.0.478 it did not experience a crash. 

Thanks for fixing this!
